### ISSUE TITLE
Configure Jenkins for Repo

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#6]

**Comment by collnell** [comment]
I made an attempt to do this, although I'm not sure if I did it correctly. Can you double check the project set up in jenkins @mwernimont ? I'd like to have a link to share by tomorrow, regardless of the state of the page itself

**Comment by mwernimont** [comment]
Do you have a URL to the jenkins @collnell ?

**Comment by collnell** [comment]
https://jenkins.wma.chs.usgs.gov/job/MakerSpace/job/snow-to-flow/

**Comment by mwernimont** [comment]
Appears to be some issues with what node we are trying to use to run the job.  Going to look into it

**Comment by mwernimont** [comment]
Talked to Megan and she has some question:

Are you expecting the jenkins to use the jenkinsfile on github?  If so it is currently not referenced in the pipeline section of the build.  If you want the jenkinsfile to be read you need to create a pipeline job like this https://jenkins.wma.chs.usgs.gov/job/MakerSpace/job/delaware-story-build-deploy/configure
It might be worth trashing this current job and duplicating the Delaware build job and filling in the correct info.  

Just as a heads up I am not a jenkins guy.  I have setup 0 jobs in my lifetime lol.  Even as I type out what Megan said I am getting confused.

**Comment by collnell** [comment]
Thanks Marty. I thought I was copying another project's job correctly but turns out I was making it more complicated than it is. There's a "copy other project" button when you first create a new project that should be used to duplicate the prior set up. Test is up now.

![image](https://user-images.githubusercontent.com/17803537/108398622-d5e27a80-71de-11eb-9936-da9a3e292378.png)

For future reference, Aaron gives a detailed explanation on this ~43 min here: https://web.microsoftstream.com/video/49488971-14b2-431e-9d9a-f3f0b5695775
