### ISSUE TITLE
Edit Existing Header Component

### ISSUE THREAD

**Issue by ellenbechtel** [USGS-VIZLAB/snow-to-flow#8]
The current [header ](https://github.com/USGS-VIZLAB/snow-to-flow/blob/master/src/views/header/Header.vue)is mostly a copy-pasta from a codepen example on scrubbing. We'll having to change the photo layers it uses (for copyright reasons, and because John Hammond has some awesome photos that we want to feature), but the general concept and function we want to stay the same.

We'll take care of getting photos and stuff from John, so don't worry about the actual images/layers themselves for a bit.

Can you please: 

- Change any structural things that make this code block more Vue-friendly, performance wise
- Consider any glaring mobile-responsive issues that a code block like this would pose (like, will safari on iphones fall over and die if it tries to load parallax scrolling like this?)

**Comment by mwernimont** [comment]
I have looked at this and a few things come up.

It currently isn't mobile friendly:

- Tiny text inside the SVG due to having to transform with the SVG size which makes it pretty hard to read.
- The animation and section spacing (sections overlapping one another) gets all messed up due to the image getting smaller but all the same settings being set in the JS.  
- I think this has to do with the sizing issue again but the animations chug a bit on mobile as well.

The parallax also works differently depending on screen width and heights.

I'm currently looking into proper responsive design for parallax websites so I'm not saying we shouldn't do it.  I think for now if you wanted to show JR your current idea with that Splash component you could for demonstration purposes.

**Comment by collnell** [comment]
The text doesn't have to be svg if that makes a difference. If we wanted to opt for another direction, we could do a more basic parallax effect with a single image, or use the `DJI_0683.mp4` file in the videos folder to do a video scrubbing effect and the page is scrolled. Open to suggestions

**Comment by mwernimont** [comment]
I still think the multiple image idea is doable, just need to rethink the structuring of it. But it is nice to have backups.
